"""initial PostgreSQL schema

Revision ID: 001
Revises:
Create Date: 2026-05-05
"""
from alembic import op

revision = "001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
        CREATE TABLE IF NOT EXISTS platforms (
            id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name         TEXT NOT NULL UNIQUE,
            display_name TEXT NOT NULL
        )
    """)

    op.execute("""
        CREATE TABLE IF NOT EXISTS accounts (
            id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            platform_id INTEGER NOT NULL REFERENCES platforms(id),
            account_key TEXT NOT NULL,
            label       TEXT,
            UNIQUE(platform_id, account_key)
        )
    """)

    op.execute("""
        CREATE TABLE IF NOT EXISTS batches (
            id          TEXT PRIMARY KEY,
            started_at  TEXT NOT NULL,
            finished_at TEXT,
            status      TEXT NOT NULL DEFAULT 'running'
        )
    """)

    op.execute("""
        CREATE TABLE IF NOT EXISTS source_runs (
            id            TEXT PRIMARY KEY,
            batch_id      TEXT NOT NULL REFERENCES batches(id),
            account_id    INTEGER NOT NULL REFERENCES accounts(id),
            started_at    TEXT NOT NULL,
            finished_at   TEXT,
            status        TEXT NOT NULL DEFAULT 'running',
            error_message TEXT
        )
    """)

    op.execute("""
        CREATE TABLE IF NOT EXISTS raw_payloads (
            id            TEXT PRIMARY KEY,
            source_run_id TEXT NOT NULL REFERENCES source_runs(id),
            resource_type TEXT NOT NULL,
            file_path     TEXT NOT NULL,
            payload_hash  TEXT NOT NULL,
            fetched_at    TEXT NOT NULL,
            parser_status TEXT NOT NULL DEFAULT 'pending'
        )
    """)

    op.execute("""
        CREATE TABLE IF NOT EXISTS normalized_holdings (
            id                   TEXT PRIMARY KEY,
            source_run_id        TEXT NOT NULL REFERENCES source_runs(id),
            raw_payload_id       TEXT NOT NULL REFERENCES raw_payloads(id),
            platform_symbol      TEXT NOT NULL,
            platform_asset_name  TEXT,
            asset_type           TEXT NOT NULL,
            quantity             REAL NOT NULL,
            price                REAL,
            value                REAL,
            original_currency    TEXT NOT NULL,
            price_source         TEXT,
            snapshot_date        TEXT NOT NULL,
            parser_version       TEXT NOT NULL,
            chain                TEXT
        )
    """)

    op.execute("""
        CREATE TABLE IF NOT EXISTS account_snapshots (
            id            TEXT PRIMARY KEY,
            batch_id      TEXT NOT NULL REFERENCES batches(id),
            account_id    INTEGER NOT NULL REFERENCES accounts(id),
            snapshot_date TEXT NOT NULL,
            total_value   REAL,
            currency      TEXT,
            created_at    TEXT NOT NULL,
            UNIQUE(account_id, snapshot_date, batch_id)
        )
    """)

    op.execute("""
        CREATE TABLE IF NOT EXISTS portfolio_snapshots (
            id            TEXT PRIMARY KEY,
            batch_id      TEXT NOT NULL REFERENCES batches(id),
            snapshot_date TEXT NOT NULL,
            note          TEXT,
            created_at    TEXT NOT NULL
        )
    """)

    op.execute("""
        CREATE TABLE IF NOT EXISTS category_snapshots (
            id            TEXT PRIMARY KEY,
            snapshot_date TEXT NOT NULL,
            category      TEXT NOT NULL,
            total_value   REAL NOT NULL,
            currency      TEXT NOT NULL DEFAULT 'USD',
            source        TEXT NOT NULL,
            batch_id      TEXT REFERENCES batches(id),
            created_at    TEXT NOT NULL,
            UNIQUE(snapshot_date, category)
        )
    """)

    op.execute("""
        CREATE TABLE IF NOT EXISTS fx_rates (
            date   TEXT PRIMARY KEY,
            usdtwd REAL NOT NULL
        )
    """)

    op.execute("""
        CREATE TABLE IF NOT EXISTS benchmark_prices (
            date   TEXT NOT NULL,
            ticker TEXT NOT NULL,
            open   REAL,
            high   REAL,
            low    REAL,
            close  REAL,
            PRIMARY KEY (date, ticker)
        )
    """)

    # Seed platforms
    op.execute("""
        INSERT INTO platforms (name, display_name) VALUES
            ('binance',    'Binance'),
            ('okx',        'OKX'),
            ('mexc',       'MEXC'),
            ('bybit',      'Bybit'),
            ('yuanta',     '元大證券'),
            ('firsttrade', 'FirstTrade'),
            ('sui_wallet', 'SUI Wallet'),
            ('evm_wallet', 'EVM Wallet'),
            ('sol_wallet', 'Solana Wallet'),
            ('ibkr',       'IBKR')
        ON CONFLICT (name) DO NOTHING
    """)

    # Seed accounts (account_main for exchange-type platforms)
    op.execute("""
        INSERT INTO accounts (platform_id, account_key, label)
        SELECT id, 'account_main', 'Main Account'
        FROM platforms
        WHERE name IN ('binance','okx','mexc','bybit','yuanta','firsttrade','ibkr')
        ON CONFLICT (platform_id, account_key) DO NOTHING
    """)


def downgrade() -> None:
    for table in [
        "benchmark_prices", "fx_rates", "category_snapshots",
        "portfolio_snapshots", "account_snapshots", "normalized_holdings",
        "raw_payloads", "source_runs", "batches", "accounts", "platforms",
    ]:
        op.execute(f"DROP TABLE IF EXISTS {table} CASCADE")
